name: html_view
description: rendering .html file on Web Platform.
version: 0.0.2
homepage: https://github.com/scriabinEtude/html_view

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
